### ISSUE TITLE
Adding the Dashboard via Figma

### ISSUE THREAD

**Issue by ZenaguiAnas** [Soli-code-Hackahton/HackathonProject#2]

**Comment by aaiaa-1** [comment]
![Cash payment form](https://github.com/Soli-code-Hackahton/HackathonProject/assets/117121490/8c3575f1-a783-4e1a-8108-9d64eda68904)
![Client details-1](https://github.com/Soli-code-Hackahton/HackathonProject/assets/117121490/38ba499f-a1cd-494a-a6e4-d1e0fbf4bedb)
![Client details-2](https://github.com/Soli-code-Hackahton/HackathonProject/assets/117121490/1fc0655a-b5dc-4a80-820e-92ec35fe47af)
![Client details](https://github.com/Soli-code-Hackahton/HackathonProject/assets/117121490/b60b906f-ce4b-4c61-89a7-100413ec8335)
![Desktop - 1](https://github.com/Soli-code-Hackahton/HackathonProject/assets/117121490/69706db9-1f5e-4581-8584-4ab5e8b7ec84)
![Link of Payment](https://github.com/Soli-code-Hackahton/HackathonProject/assets/117121490/2d6dc722-0a06-49d3-9da2-2133d2eb1cf7)
